"""add rbac, tenants, organization, assets, tags, telemetry, employees

Revision ID: 448af0d2e461
Revises: dd1dcb53e360
Create Date: 2026-09-08 11:46:44.514907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448af0d2e461'
down_revision: Union[str, Sequence[str], None] = 'dd1dcb53e360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
