"""add enabled_modules to tenants

Revision ID: 954c8e3e765a
Revises: 448af0d2e461
Create Date: 2026-09-10 15:41:05.161579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954c8e3e765a'
down_revision: Union[str, Sequence[str], None] = '448af0d2e461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('enabled_modules', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'enabled_modules')
    # ### end Alembic commands ###
